### ISSUE TITLE
Consider disabling the disable-building-autotargeting and AssaultMove with simple YAML edits instead of commit reverting.

### ISSUE THREAD

**Issue by GraionDilach** [SoScared/Red-Alert-Unplugged#10]
Reverting commits which touch the codebase will affect the upgrading the mod longterm, in the form of possible conflicts. Take note that _all autotargeting is now based on conditions, with assault move and attack-anything stance enabling the condition required for structure autotargeting in ORA-RA_.

All you need to do is to remove the condition requirement on the AutoTargetPriority trait which enables Structures, then also remove the condition-granting lines on AttackMove and AutoTarget and you resolved your aim without any changes in the actual codebase.

**Comment by SoScared** [comment]
That sounds great, thank you! That might also help realize the idea of one day having the targeting feature enabled for the single player campaigns.

**Comment by GraionDilach** [comment]
Taking this a step further, after you removed the conditions on this, assault-move will not look different compared to attack-move at all, so you can "keep" it to use with regular attackmove cursors - it won't make a difference afterall. All you need to do thenafter is to remove the mention of it from the UI commandbar - still not requiring codebase changes IIRC, just mod yaml ones.

So yeah, you should archieve this as a modder and not as a coder - for your own good.

**Comment by SoScared** [comment]
Definitely for my own good.

With the mod upgrade looking much less scary it also then looks more prudent to launch the mod project from the current release.

**Comment by pchote** [comment]
I strongly recommend that you add these overrides in their own yaml files that you then add to your `mod.yaml`.  If you edit the default mod files then you will need to fix everything by hand when you choose to update to a newer version of the base RA mod.  If you add them as override files (similiarly to how map overrides work) then you can delete/replace the RA mod files and then only have to adjust your overrides to suit.

I intend on adding this same warning to the Mod SDK getting started page.

**Comment by SoScared** [comment]
That's great, thanks! Will definitely go down that road. Seem like an approach that can be used with plenty of other yaml changes I had in mind.

**Comment by SoScared** [comment]
PR #11 

A great timeserver and straightforward solution. Thanks for the advice!
