### ISSUE TITLE
Add the RA mod repository from OpenRA 1014 release.

### ISSUE THREAD

**Issue by SoScared** [SoScared/Red-Alert-Unplugged#7]
RAU's development begins with the latest updated bleed of OpenRA:

https://github.com/OpenRA/OpenRA

Next we'll need to isolate the RA mod repository to the master branch: 
https://github.com/SoScared/Red-Alert-Unplugged

Further updates from OpenRA's bleed relevant to the standalone mod are handled on a regular basis.

**Comment by SoScared** [comment]
Just discovered https://github.com/OpenRA/OpenRAModSDK and https://github.com/OpenRA/OpenRAModSDK/wiki/Getting-Started by pchote as a hand-holding guide on creating a new mod from scratch. Pretty neat.

**Comment by pchote** [comment]
Doing a hard fork by copy/pasteing the repository and removing all the git history is going to make it very difficult for you to merge engine changes into your project going forward.  I can't emphasise enough just how bad an idea that is, unless you are planning to cut all ties with the main OpenRA code base moving forward.

The Mod SDK provides a framework for doing this in a supported and maintainable way, and you can use https://github.com/OpenRA/raclassic as a more relevant example to follow.

**Comment by SoScared** [comment]
The current repository is just a result of me experimenting a bit just to see how things work. It'lI be replaced soon enough. I actually found the mod SDK pages just yesterday, and through ra classic as well!  Seem like the proper way to go. Great guide!

**Comment by SoScared** [comment]
With the planned feature repealing looking like could be done without butchering tons of code (#10 ) I'm starting off with the release 1014 as a starting point. Seem like an inevitable path, as perhaps it always was.

**Comment by SoScared** [comment]
Added RA clone from 1014 release.
